theme: minima

collections:
  docs:
    output: true
    permalink: /docs/:slug

title: coding and research blog
description: >- 
  General purpose coding and research blog covering my personal projects. The
  code described here includes both personal interest projects and research-
  relevant materials. If you use it in your research, consider citing me!

plugins:
  - jekyll-feed

gems:
  - jekyll-font-awesome-sass

